### PR TITLE
feat(core): add external validations support

### LINKED ISSUE #824: Displaying external validation errors
**Is your feature request related to a problem? Please describe.**
Vuelidate does a great job with client-side validation, but sometimes we need to implement server-side validation as well. I know it is possible to add custom validations, but what if the only method to find out about errors is to submit a form?

Here's a simple example:
https://codesandbox.io/s/eager-clarke-nmz2q

I would like to be able to nicely display the errors that occurred after the form was submitted. Is it possible? Unfortunately, I was unable to find a solution.

**Describe the solution you'd like**
It would be great to be able to inject temporary error messages that go away as soon as the user interacts with the form.

**Describe alternatives you've considered**
Now we have to use various crutch solutions, for example:
https://blog.philiphendry.me.uk/2020/01/09/integrating-server-side-errors-with-vuelidate
https://stackoverflow.com/questions/55497881/vuelidate-server-side-validation

**Additional context**
https://github.com/vuelidate/vuelidate/issues/277

### PR DESCRIPTION
**Pull request by dobromir-hristov**
## Summary

Adds external validator support to Vuelidate. For each state property, we can have a validation error from the server. It can be a single string or even an array of errors. closes #824 

```
const state = {
  child: 'a',
  nested: {
    nestedChild: 'b'
  }
}

const externalErrors = {
  child: 'Child is not Valid',
  nested: {
    nestedChild: ['Foo', 'bar']
  }
}
```

This adds a `$externalResults` key to the Vuelidate validation object as well as triggers both `$invalid` and `$error` if said property external results are not empty.

## Usage in Composition API

```js
const state = {
  number: 0
}
const $externalResults = ref({});
const v = useVuelidate(rules, state, { $externalResults })

async function addExternalErrors(){
 $externalResults.value = { number: 'Must be above 0' }
}
```

## Usage with Options API

If you need to have external results, just create a `vuelidateExternalResults` object, preferably with the same structure as your state, in the instance data.

```js
export default {
  data: () => ({
    name: 'foo',
    vuelidateExternalResults: { name: 'Must Not be Foo' }
  })
}
```

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuelidate/vuelidate/blob/master/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rjd22** [comment]
This functionality seems extremely useful. @dobromir-hristov can I help with this?

**Comment by dobromir-hristov** [comment]
I think it was mostly done, just need to double check with latest changes to next branch, and if it works with object API.

**Comment by dobromir-hristov** [comment]
I think we could have probably went without `vuelidateExternalResults` on the OptionsAPI and instead tell people to pass a ref to the `useVuelidate` config instead, but thats mixing the two concepts so I would rather we dont do that.

**Comment by rjd22** [comment]
@dobromir-hristov I also think that having a clear input and output is way more sensible. injecting refs that will be changed feels really familiar to a double dispatch, that might be confusing to most developers.

**Comment by entermix** [comment]
@dobromir-hristov Thanks!

**Comment by c0depwn** [comment]
With what npm package version will this be available? With the current latest version of `^2.0.0-alpha.19` this functionality does not seem to be available. I have just noticed this since the `GlobalConfig` type is missing the `$externalResults`. Is there a workaround or will I just have to wait for the next release?

**Comment by dobromir-hristov** [comment]
I think I have not released it yet. Should be out soon.

**Comment by c0depwn** [comment]
@dobromir-hristov Alright thanks  I'm really looking forward to this feature, great stuff! 🙂 I was a bit disappointed since the docs already have an example of this.

**Comment by dobromir-hristov** [comment]
It should be out now, please give it a try.

**Comment by c0depwn** [comment]
@dobromir-hristov Thank you for the quick response/release! 

Unfortunately I have noticed some breaking issues with the implementation:
1. Using  `const $externalResults = ref({});` as described in the docs and passing it like this  `const v$ = useVuelidate(rules, state, { $lazy: true, $externalResults });` will result in the following type error: `Type 'Ref<{}>' is not assignable to type 'ServerErrors'`. I cannot type`ref<ServerErrors>({})` since `ServerErrors` is not exported.
2. Additionally, `GlobalConfig` now requires the argument `$externalResults` which breaks all existing implementations not using this features, I'm referring to the following:
```
interface GlobalConfig {
  $registerAs?: string
  $scope?: string | number | symbol | boolean
  $stopPropagation?: boolean
  $autoDirty?: boolean
  $lazy?: boolean,
  $externalResults: ServerErrors <-- this should probably be optional ($externalResults?)
}
```

I'm currently using typescript and vue 3. If you want I can create a separate issue. But for now until these problems are addressed I will have to downgrade and use a workaround. I hope this is helpful.

**Comment by dobromir-hristov** [comment]
Please create a PR to fix the TS issues. I cannot do that atm.

**Pull request merged**
