### PR TITLE
fix(email validator): update email regex validator

### PR DESCRIPTION
**Pull request by warna720**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuelidate/vuelidate/blob/master/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

With inspiration from https://github.com/vuelidate/vuelidate/pull/715 but a bit updated to not break tests

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
Awesome! Did you try his case as well?

**Comment by AllanOricil** [comment]
Could you add `joão@gmail.com` and run the tests again.

**Comment by AllanOricil** [comment]
@warna720 Besides `joão@gmail.com` another test I was concerned is the one below:

````javascript
it('should validate real addresses', () => {
 ...
 expect(email('"some one"@gmail.com')).to.be.true
}
````

On HTML 5 that email is expected to be fale/invalid, but on the unit tests it is marked as a valid email. Could you try to fix it on the regex?

On this PR I think we should also add changes on the DOC to make people aware that there is no "perfect" regex for email validation, so they should  use this `email` rule carefully.

**Comment by AllanOricil** [comment]
https://github.com/vuelidate/vuelidate/issues/710

**Comment by warna720** [comment]
> @warna720 Besides `joão@gmail.com` another test I was concerned is the one below:
> 
> ```js
> it('should validate real addresses', () => {
>  ...
>  expect(email('"some one"@gmail.com')).to.be.true
> }
> ```
> 
> On HTML 5 that email is expected to be fale/invalid, but on the unit tests it is marked as a valid email. Could you try to fix it on the regex?
> 
> On this PR I think we should also add changes on the DOC to make people aware that there is no "perfect" regex for email validation, so they should use this `email` rule carefully.

Since RFC5322 permits whitespace (and other characters) surrounded with quotes, I think its OK. I added a test for whitespace without surrounding quotes. PR is now updated with more tests.

**Review by dobromir-hristov — APPROVED** [review]
Awesome work!

**Comment by warna720** [comment]
> Awesome work!

Great. How do we proceed? Will you be merging?

**Comment by dobromir-hristov** [comment]
Ping @shentao for a quick look, then we merge.

**Comment by shentao** [comment]
I am completely unfamiliar with the regex best practices. 😅 But as long as the tests pass and make sense, I guess LGTM.

**Comment by AllanOricil** [comment]
Nice job. Now I can progress with it on my work.
Now, regarding to that other email. if people declare `<input type="email" v-model="myEmailInputData"/>` and pass ``"some one"@gmail.com`  to the input, it will be wrong for HTML 5.

**Comment by warna720** [comment]
Nice, how can I get this update? We are on Vue2 and version 0.7.5 of vuelidate.

**Comment by dobromir-hristov** [comment]
@warna720 we need to release first. Unfortunately this PR is for the next version, which is still alpha. We would have to backport it to Vuelidate 0.x

@AllanOricil you have a point, unfortunately I am far from able to fix that regex :(

**Comment by warna720** [comment]
> Nice job. Now I can progress with it on my work.
> 
> Now, regarding to that other email. if people declare `<input type="email" v-model="myEmailInputData"/>` and pass ``"some one"@gmail.com` to the input, it will be wrong for HTML 5.

I just checked, HTML5 doesnt like either " or whitespace.

**Comment by warna720** [comment]
> @warna720 we need to release first. Unfortunately this PR is for the next version, which is still alpha. We would have to backport it to Vuelidate 0.x

Alright, can you give an estimate until its released and backported? E.g. a month, a year etc.

**Comment by AllanOricil** [comment]
> @warna720 we need to release first. Unfortunately this PR is for the next version, which is still alpha. We would have to backport it to Vuelidate 0.x
> 
> @AllanOricil you have a point, unfortunately I am far from able to fix that regex :(

Im unable too haha.
But it would be nice to just add it on the DOC so people don't just do validation on their frontend and save on a text field on the database. You know?
They will complain that Vuelidate was causing that. But if it is declared on the Doc and removed from the tests, then they will not blame the lib for that.

**Comment by warna720** [comment]
ping @dobromir-hristov

**Comment by dobromir-hristov** [comment]
Hey sorry i Totally forgot about this... Can you make a new issue so we can track the backport of the validator to old Vuelidate?

I will do a release with it later.

**Pull request merged**
