### PR TITLE
Security fix for ReDoS

### PR DESCRIPTION
**Pull request by ready-research**
Fixed Regular Expression Denial of Service vulnerability in URL validation
Reported in https://www.huntr.dev/bounties/d8201b98-fb91-4c12-a6f7-181b4a20d9b7

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuelidate/vuelidate/blob/master/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
Interesting. I honestly am not sure if this is an improvement or not. Never heard of that website before as well lol

Will do some testing over the weekend

**Comment by ready-research** [comment]
@dobromir-hristov Any update on this?

**Comment by dobromir-hristov** [comment]
@ready-research can you fix the failing tests? Honestly 

Also can you give a bit more info into what you fixed and how? Regex is always a pain to get.

**Comment by ready-research** [comment]
@dobromir-hristov You can find more information about the vulnerability in [huntr](https://www.huntr.dev/bounties/d8201b98-fb91-4c12-a6f7-181b4a20d9b7/) and also can you please validate that issue in huntr using validate button.

I am not sure how to fix the test cases. Feel free to make changes if required or to add test cases.
You can [refer](https://securitylab.github.com/advisories/GHSL-2020-293-redos-react-native/) as well to know about this issue in detail. Thank you.

**Comment by dobromir-hristov** [comment]
You created the PR, you have to make sure your change does not break the test suite.

You can run the test suite using `npm run test:all`.

As for the code fix, I see it is identical to the regex in https://gist.github.com/dperini/729294.

**Comment by ready-research** [comment]
@dobromir-hristov Can you validate this https://www.huntr.dev/bounties/d8201b98-fb91-4c12-a6f7-181b4a20d9b7 in huntr by clicking validate button and also confirm the fix.

**Pull request closed without merging**
