### PR TITLE
docs: custom error messages (fix #748)

### LINKED ISSUE #748: Misleading explanation when changing errors messages in the docs
## The text
From [https://vuelidate-next.netlify.app/guide.html#displaying-error-messages](url) 
<blockquote><p>Error messages come out of the box with the bundled validators in <code>@vuelidate/validators</code> package. You can check how change those them over at the <a href="./custom_validators.html">Custom Validators page</a></p></blockquote>

## The problem

After navigating to <a href="https://vuelidate-next.netlify.app/custom_validators.html">Custom Validators page</a>, I still don't know how to change the error messages. 
IMO, it lacks a proper explanation otherwise it may mislead the reader.

### PR DESCRIPTION
**Pull request by aethr**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Docs update

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuelidate/vuelidate/blob/master/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by aethr** [comment]
@shentao or @dobromir-hristov I just wrote this based on reading the code, so I've made a few assumptions.

Would it also be fine for users to define custom validators with messages using the object syntax? I.e.:

```js
    const isEven = {
      $validator: (val) => val.length % 2 === 0,
      $message: 'Length must be even',
    };
```

If so I can add another section.

**Comment by dobromir-hristov** [comment]
Hey, yeah it's fine, but probably better to use the helper.

The explanation is alright as well. We should mention the message is reactive and if props change, it also changes.

**Review by shentao — APPROVED** [review]
Love it! 
One question though, should we perhaps switch the order of arguments for this helper?

**Comment by aethr** [comment]
I suppose the order doesn't bother me too much, I think if you have a lot of basic string messages, having that argument first kind of helps to make it self documenting? If you're using a lot of functions that are defined in-line, it might not be as easy to read.

I'd say the most important thing is that it's consistent with any other `with*` helpers like `withParams`.

**Pull request merged**
