### PR TITLE
feat(validators): add "phoneNumber" validator

### PR DESCRIPTION
**Pull request by Roninii**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuelidate/vuelidate/blob/master/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
> It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch

It's submitted to the `next` branch

### CODE REVIEW

**Comment by AllanOricil** [comment]
Phone numbers are hard to validate because they vary a lot across multiple countries.
We usually use libs to apply masks, like this https://www.npmjs.com/package/vue-the-mask,  or libs that handle multiple country phones like this https://louismazel.github.io/vue-phone-number-input/

What I would suggest is to have a list of multiple Regex for each country and the Validator would accept a parameter to choose the country or countries. This input would be the official ISO codes.

````
phone: phone('BR')
````
````
phone: phone(['BR', 'PT', 'US'])
```

Or

use a external service to validate the emails without regex, but accepting the ISO code as an input for the validator.

What do you think? @dobromir-hristov @shentao @Roninii

**Comment by Roninii** [comment]
I think that approach makes sense. Maintaining multiple regex checks for this lib _might_ be pushing the scope though. Interested to see what the others have to say about it.

**Comment by dobromir-hristov** [comment]
I think we should leave the phone validator for now. It is too specific to be a simple validator that fits all.

As discussed, there are entire libraries for that, and most people rely on them already for formatting the inputs. Most of them have validators baked in. 

If you want to go into an adventure and try to cover as many as you can, by providing a nice API for users to use, then you can make a small mini package, like `vuelidate-plugin-phone-validators` or something 😄 

We will link it to docs :)

**Comment by dobromir-hristov** [comment]
@shentao wdyt?

**Comment by shentao** [comment]
I’m also in favor of having a separate library for the phone validator that we could recommend in the docs. Given how broad is the topic, I’m afraid we would end up with a constant stream of issues related to certain phone number formats, that would detract us from working on Vuelidate core.

**Comment by Roninii** [comment]
After all the discussion, I think everyone is in agreement. The original estimate of the scope was way smaller. Going to close this.

**Pull request closed without merging**
