### PR TITLE
fix #743 - VuelidatePlugin ts type to accept App argument

### LINKED ISSUE #743: Vue 3 Install Error
- vue 3.0.2
- vuelidate/core 2.0.0-alpha.6
- vuelidate/validators 2.0.0-alpha.4

main.ts:
```ts
import App from '@/App.vue'
import { VuelidatePlugin } from '@vuelidate/core'
import { createApp } from 'vue'

const app = createApp(App)

app.use(VuelidatePlugin).mount('#app')
```

error on line 7 (`.use(VuelidatePlugin)`):
```
Argument of type '(app: DefineComponent<readonly string[] | Readonly<ComponentObjectPropsOptions<Record<string, unknown>>>, unknown, unknown, Record<string, ComputedGetter<any> | WritableComputedOptions<...>>, ... 7 more ..., { ...; } | {}>) => void' is not assignable to parameter of type 'Plugin_2'.
  Type '(app: DefineComponent<readonly string[] | Readonly<ComponentObjectPropsOptions<Record<string, unknown>>>, unknown, unknown, Record<string, ComputedGetter<any> | WritableComputedOptions<...>>, ... 7 more ..., { ...; } | {}>) => void' is not assignable to type 'PluginInstallFunction & { install?: PluginInstallFunction | undefined; }'.
    Type '(app: DefineComponent<readonly string[] | Readonly<ComponentObjectPropsOptions<Record<string, unknown>>>, unknown, unknown, Record<string, ComputedGetter<any> | WritableComputedOptions<...>>, ... 7 more ..., { ...; } | {}>) => void' is not assignable to type 'PluginInstallFunction'.
      Types of parameters 'app' and 'app' are incompatible.
        Type 'App<any>' is not assignable to type 'DefineComponent<readonly string[] | Readonly<ComponentObjectPropsOptions<Record<string, unknown>>>, unknown, unknown, Record<string, ComputedGetter<any> | WritableComputedOptions<...>>, ... 7 more ..., { ...; } | {}>'.
          Type 'App<any>' is not assignable to type 'ComponentPublicInstanceConstructor<({ $: ComponentInternalInstance; $data: {}; $props: (Partial<{ [x: number]: string; }> & Pick<(Readonly<{ [x: number]: string; } & { length?: number | undefined; ... 21 more ...; flat?: unknown[] | undefined; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps) | (Readon...'.
            Type 'App<any>' provides no match for the signature 'new (...args: any[]): ({ $: ComponentInternalInstance; $data: {}; $props: (Partial<{ [x: number]: string; }> & Pick<(Readonly<{ [x: number]: string; } & { length?: number | undefined; ... 21 more ...; flat?: unknown[] | undefined; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps) | (Readonly<...> & ... 3 more ... & Readonly<...>) | (Readonly<...> & ... 3 more ... & Readonly<...>) | (Readonly<...> & ... 2 more ... & ComponentCustomProps), "length" | ... 53 more ... | ((<A, D extends number = 1>(this: A, depth?: D | undefined) => FlatArray<...>[]) & string)>) | (Partial<...> & Pick<...>); ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; } & ... 4 more ... & ComponentCustomProperties) | ({ ...; } & ... 4 more ... & ComponentCustomProperties)'.ts(2345)
```

Project was set up through Vue CLI, not sure that makes any difference.

### PR DESCRIPTION
**Pull request by aethr**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuelidate/vuelidate/blob/master/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by aethr** [comment]
Hopefully this fixes #743 .

**Comment by dobromir-hristov** [comment]
I am fine with merging, did you try it out?

**Comment by aethr** [comment]
It worked with a fresh project created using vue-cli with TypeScript support. I made this change to the `@vuelidate/core` types definition in the `node_modules` folder of the test project and the error went away.

**Comment by mycarrysun** [comment]
This is currently broken...getting the error 
```
node_modules/@vuelidate/core/index.d.ts:160:37 - error TS2304: Cannot find name 'App'.

160 export const VuelidatePlugin: (app: App) => void;
                                        ~~~


Found 1 error.
```

Going to put up a PR now but where should the `App` type come from? Looks like its not imported from anywhere

**Comment by dobromir-hristov** [comment]
Yeah i saw... From vue-demi, it relays it from Vue.

**Comment by mycarrysun** [comment]
Looks like `Plugin` is the proper type to use so I put up a PR

**Comment by gregveres** [comment]
@mycarrysun Plugin is not the proper type. Well, it is the proper type for building with Vue 3, but it is not the proper type for Vue 2. Plugin doesn't exist in Vue 2. This change is now causing build errors for Vue 2 use.

**Comment by dobromir-hristov** [comment]
@gregveres why not try fixing it :) I see you found the culprit.

**Pull request merged**
