### PR TITLE
ValidationRule should accept boolean to cater $autoDirty: true

### PR DESCRIPTION
**Pull request by kayue**
ValidationRule should accept boolean to cater `$autoDirty: true`

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
You sure about this? A validation rule has to be a function or an object. I dont see how it can be a boolean.

**Comment by shentao** [comment]
I’m also not sure how this should work. @kayue could you elaborate a bit more about this use case?

**Comment by kayue** [comment]
`$autoDirty: true` is one of the ValidationRule. 

Please see https://vuelidate-next.netlify.app/guide.html#the-dirty-state

**Comment by dobromir-hristov** [comment]
It's a property, but the entire validation cannot be a boolean. Maybe it's me and I don't get how we should refactor the type better.

**Comment by dobromir-hristov** [comment]
I am going to close this. A validator can two things, sorry of my TS lingo is wrong here... But it cannot be just a boolean

```ts
const Validator = Function

interface Validator {
  $validator: Function,
  $autoDirty?: Boolean,
  $lazy?: Boolean,
  $params?: Object
}
```

**Comment by kayue** [comment]
@dobromir-hristov Thanks for following up. I thought I was modifying `ValidationRule` (not validator), which in your example it can be "Function, Boolean and Object".

I will cycle back when I can reproduce this, I am in another project now.

Thanks.

**Comment by kayue** [comment]
@dobromir-hristov this is the error that I ran into
Screenshot 2021-03-26 at 12 44 37 AM

**Comment by dobromir-hristov** [comment]
We should tell it that a validator can accept configuration, not a raw boolean.

If you can do that, would be awesome

**Comment by kayue** [comment]
@dobromir-hristov Sorry not an expert in defining type, I don't understand what you meant.

**Comment by dobromir-hristov** [comment]
Then you will have to wait for one of us to fix it. I may try this weekend.

For now, You can just pass the configs as the third parameter to useVuelidate, they will be passed to ass validators.

**Pull request closed without merging**
