### PR TITLE
Fix/email validator

### PR DESCRIPTION
**Pull request by AllanOricil**
**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [X] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [X] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

This regex expression comes from a revision of the official specification for email formats (RFC2822). This is the [RFC5322](https://tools.ietf.org/html/rfc5322) and it was not written by me. I got it from [here](https://emailregex.com/). With this spec the email 'joão@example.com' becomes invalid like it is on the HTML 5 input type = 'email'. But 4 Unit tests failed.

image

1 - `"someone@gmail.com`  is now valid
2 - `someone@gmail.c` is now valid
3 - `someone@gmail.com ` is now valid
4 - `"some one"@gmail.com` is now invalid -> which makes sense. I think we should review this one because on the test it says it should be true, but I never saw any emails like that. I think it is wrong, which is good.

```
it('should validate real addresses', () => {
 ...
 expect(email('"some one"@gmail.com')).to.be.true
}
```

**The PR fulfills these requirements:**

OBS: I could not find the dev branch. Is it the `next`? or the `next` is just for approved changes?

- [ ] It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuelidate/vuelidate/blob/master/.github/CONTRIBUTING.md#development-setup
- [X] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [X] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)
It will follow a "official spec" for emails formats.

**Other information:**

### CODE REVIEW

**Comment by AllanOricil** [comment]
I hope we can discuss about the failing unit tests.

**Comment by dobromir-hristov** [comment]
Hey, thanks for your work. 

Can you do the change against the `next` Branch?

Now for the failing tests, some of them are concerning. 
The 1 and 3 one should deff be invalid.
4 should also be invalid IMHO

**Comment by AllanOricil** [comment]
> Hey, thanks for your work.
> 
> Can you do the change against the `next` Branch?
> 
> Now for the failing tests, some of them are concerning.
> The 1 and 3 one should deff be invalid.
> 4 should also be invalid IMHO

@dobromir-hristov I just tried to add the changes to the next branch but all the Jest tests suites are failling to me. Even without the changes. Did you test run those tests on windows? All the errors are related to the same thing, look

image

Can I just create the PR with the 2 changes?

**Comment by dobromir-hristov** [comment]
the next branch is entirely new app, written for Vue 3 and backported for Vue 2. You should just be able to run it fine after running `yarn install`

**Comment by warna720** [comment]
Hi, I submitted a PR solving this https://github.com/vuelidate/vuelidate/pull/718

**Comment by AllanOricil** [comment]
> Hi, I submitted a PR solving this #718

@warna720 cool. Thanks for that I was occupied with other stuff.
So you used the RF5322?

**Comment by AllanOricil** [comment]
I will close this and we continue using @warna720 PR

**Pull request closed without merging**
