### PR TITLE
Add support for function validators to `withI18nMessage`

### PR DESCRIPTION
**Pull request by wvffle**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuelidate/vuelidate/blob/master/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
The `withI18nMessage` function proposed in the https://vuelidate-next.netlify.app/advanced_usage.html#i18n-support does not seem to work with function validators like `minLength`. I modified the function for it to be able to handle those validators well.

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
Good catch, i just did that in 5 mins hehe. I will think about how to implement this with full compatibility.

We may need to bring this into the library directly, as it may become a bit more complicated. We need to figure out how users would provide their own translation instance.

**Comment by wvffle** [comment]
Since `withMessage` takes function as first argument, `withI18nMessage` could take i18n instance instead.

**Comment by dobromir-hristov** [comment]
> Since `withMessage` takes function as first argument, `withI18nMessage` could take i18n instance instead.

In most cases, you have a single i18n instance on your app, so I think it makes sense to have a factory function instead, that returns some "instance" of a `withI18nMessage`.

Something like this:

```js
import { createTranslatableMessages } from '@vuelidate/validators'
import i18n from '@/i18n'

export const withTranslation = createTranslatableMessages({ t: i18n.t })

// @/validators.js

export const required = withTranslation(validators.required)
export const minLength = withTranslation(validators.minLength)

// @/Form.vue

const validations = {
  name: {
    required,
    minLength: minLength(10)
  }
}
```

**Comment by dobromir-hristov** [comment]
Looked into this, and the code below works great, I would have never thought to call the function on itself 😆 great job.

```js
import withMessage from './withMessage'

export default function createI18nMessage (t) {
  const withI18nMessage = (validator, args = null) => {
    if (typeof validator === 'function' && args === null) {
      return (...args) => withI18nMessage(validator, args)
    }
    return withMessage((props) => t(`messages.${props.$validator}`, {
      model: props.$model,
      property: props.$property,
      ...props.$params
    }), args === null ? validator : validator(...args))
  }
  return withI18nMessage
}
```

I am worried however about the TS users. I have been trying to create the types for this and I am hitting a wall...

**Comment by wvffle** [comment]
I have never written any TS types, so I cannot help. Also if you want to push it as a feature, I'd rewrite it as:

```js
import withMessage from './withMessage'

export default function createI18nMessage (t) {
  const translate = (props) => t(`messages.${props.$validator}`, {
    model: props.$model,
    property: props.$property,
    ...props.$params
  })
    
  const withI18nMessage = (validator) => {
    if (typeof validator === 'function') {
      return (...args) => withMessage(translate, validator(...args))
    }
    
    return withMessage(translate, validator)
  }
  
  return withI18nMessage
}
```

**Comment by dobromir-hristov** [comment]
That i think wont work if you just pass a simple validator as a function, right?

```js
const isTrurthy = (value)=> !!value

withI18n(isTrurthy)

```

**Comment by dobromir-hristov** [comment]
Check #894, let me know what you think.

**Comment by dobromir-hristov** [comment]
I am closing this PR, #894 should cover it.

**Pull request closed without merging**
