### PR TITLE
fix: Updated useVuelidate global config types

### PR DESCRIPTION
**Pull request by ssiegel2**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

Fixed the typings for `useVuelidate` to include the global config.

### CODE REVIEW

**Review by dobromir-hristov — APPROVED** [review]
Awesome!

**Comment by shentao** [comment]
Nice! @dobromir-hristov shouldn’t we also have $lazy and $autoDirty here though?

**Comment by dobromir-hristov** [comment]
Correct, those propagate down.

**Comment by ssiegel2** [comment]
Added those missing properties. The JSDoc comments are out of sync, but I found them in the docs.

**Review by dobromir-hristov — APPROVED** [review]
Awesome

**Pull request merged**
