### PR TITLE
feat: replace vue-cli with vite

### PR DESCRIPTION
**Pull request by dobromir-hristov**
This replaces the vue-cli test-app with Vite. We dont gain much, but its a nice start.

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
I think next steps are to add a simple vue-router so we can have a nice app to do e2e tests against.

**Comment by shentao** [comment]
Looks good! I was thinking about VitePress but it’s still not that stable when it comes to production build (https://github.com/vuejs/vitepress/issues/12).

**Comment by dobromir-hristov** [comment]
For docs maybe, but not e2e app

**Comment by shentao** [comment]
Is there anything wrong with running e2e on the docs examples though?

**Comment by dobromir-hristov** [comment]
I dont see a reason why. We can have much more detailed test cases, without making them user friendly

**Comment by shentao** [comment]
True that!

**Pull request merged**
