### PR TITLE
fix: declare second sameAs validator parameter as optional (#773)

### PR DESCRIPTION
**Pull request by khorsky**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: TypeScript declaration fix

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuelidate/vuelidate/blob/master/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Forgotten question mark, I guess...

### CODE REVIEW

**Review by dobromir-hristov — COMMENTED** [review]
Technically true, though I dont think anyone will want `The value must be equal to the other value`


I think we should force that second parameter

**Comment by shentao** [comment]
I assume this is for the built-in validator already with message, right? So if someone wants to use the `sameAs` validator but without the requirement on the name of the 2nd param, they can use the raw validator directly or build a validator on top of it that has a different message format. 

On the other hand, if someone would like to modify the existing built-in validator with `withMessage` then that 2nd param becomes potentially unnecessary.

**Comment by khorsky** [comment]
Currently I set rules for `sameAs` this way:
```
const rules = {
  newPassword: {
    required,
  },
  controlPassword: {
    sameAs: sameAs(newPassword),
  },
}
// ...
```

TS compiler is complaining about missing second parameter for `sameAs.` I'm sorry if I haven't understand your thoughts, but I'd believe that second parameter should be optional.

**Comment by shentao** [comment]
@dobromir-hristov I guess if someone doesn’t care about the error message then I think we should make it optional. No harm in that.

**Comment by dobromir-hristov** [comment]
Though the same.

**Pull request merged**
