### PR TITLE
Bugfix #552 email doesn't validate for leading dash infront of domain

### PR DESCRIPTION
**Pull request by pedroresende**
This PR addresses the issue [552](https://github.com/vuelidate/vuelidate/issues/552)

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
Please add a test case for the intended fix

**Comment by pedroresende** [comment]
@dobromir-hristov Just `--amend` with the unit tests

**Comment by pedroresende** [comment]
I had to make some changes, since domains with only one character aren't valid

**Comment by pedroresende** [comment]
@dobromir-hristov just to know if anything is missing?

**Comment by christopher-avila** [comment]
How is this PR going?

**Comment by pedroresende** [comment]
@christopher-avila waiting for a new review

**Comment by dobromir-hristov** [comment]
Sorry for the wait there... just did a release.

**Pull request closed without merging**
